# Generated by Django 4.1.7 on 2023-03-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.association')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
